import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CartDrawer from "@/components/CartDrawer";
import Link from "next/link";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <CartDrawer />

        <footer className="bg-stone-100 border-t border-stone-200 mt-20 py-10">
          <div className="max-w-6xl mx-auto px-6 flex justify-between items-center text-stone-400 text-sm">
            <p>© 2025 Harvest & Hearth Organic Farm</p>
            <div className="flex gap-6">
              <Link
                href="/admin/orders"
                className="hover:text-green-700 font-medium"
              >
                Farmer Login (Admin)
              </Link>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
